# Generated by Django 4.0.6 on 2022-07-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('name', models.CharField(default=None, max_length=50)),
                ('title', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
